on:
  schedule:
    - cron: "5 2 * * 2,3,4,5,6"
  workflow_dispatch:

jobs:
  update_badges:
    name: Update the list of badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests      
      - name: Run the Python file
        run: python .github/scripts/update_badges_js.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:GITHUB_TOKEN@github.com/${{ github.repository }}
          git add ./kongregate/badges.js
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update badges"
            git pull --rebase --autostash
            git push origin
          else
            echo "No changes.";
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
