on:
  schedule:
    - cron: "0 7 * * *"
    - cron: "5 17 * * *"
    - cron: "5 1 * * *"
  workflow_dispatch:

jobs:
  update_botd:
    name: Update the badge of the day
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests      
      - name: Run the Python file
        run: python .github/scripts/update_botd_js.py
      - name: Commit changes
        run: |
          git config --global user.email "127596209+Matrix4348@users.noreply.github.com"
          git config --global user.name "Workflow"
          git remote set-url origin https://x-access-token:GITHUB_TOKEN@github.com/${{ github.repository }}
          git add ./kongregate/botd.js
          git commit --allow-empty -m "Update badge of the day"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
